[profile.default]
fs_permissions = [{ access = "read-write", path = "./test/fixtures" }]
src = "src"
test = "test"
script = "script"
out = "out"
cache_path = "cache"
solc_version = "0.8.28"
evm_version = "cancun"
optimizer = true
optimizer_runs = 20_000
via_ir = true
bytecode_hash = "none"
cbor_metadata = false

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"
quote_style = "double"

[fuzz]
runs = 1_000

[invariant]
runs = 256
depth = 64
fail_on_revert = false
