import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const sdkRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const contractsRoot = resolve(sdkRoot, "..");

const contracts = [
  ["projectLauncherV2Abi", "ProjectLauncherV2"],
  ["projectRegistryV2Abi", "ProjectRegistryV2"],
  ["projectVotesTokenAbi", "ProjectVotesToken"],
  ["projectLiquidVotesWrapperV2Abi", "ProjectLiquidVotesWrapperV2"],
  ["projectMultisigAccountV2Abi", "ProjectMultisigAccountV2"],
  ["projectGovernorV2Abi", "ProjectGovernorV2"],
  ["projectTimelockV2Abi", "ProjectTimelockV2"],
  ["projectTreasuryVaultV2Abi", "ProjectTreasuryVaultV2"],
  ["projectRouterV2Abi", "ProjectRouterV2"],
  ["projectStakingPoolV2Abi", "ProjectStakingPoolV2"],
  ["projectPoSNftAbi", "ProjectPoSNFT"],
  ["projectAirdropV2Abi", "ProjectAirdropV2"],
  ["basketManagerV2Abi", "BasketManagerV2"],
  ["basketVaultV2Abi", "BasketVaultV2"],
  ["basketNftV2Abi", "BasketNFTV2"],
  ["projectFundingBandsV2Abi", "ProjectFundingBandsV2"],
  ["projectRaffleV2Abi", "ProjectRaffleV2"],
  ["projectLiquidityManagerV2Abi", "ProjectLiquidityManagerV2"],
  ["erc4626BasketYieldAdapterAbi", "ERC4626BasketYieldAdapter"],
  ["erc4626BasketYieldAdapterFactoryAbi", "ERC4626BasketYieldAdapterFactory"],
  ["yieldBankPublicFactoryAbi", "YieldBankPublicFactory"],
  ["yieldBankCollectionAbi", "YieldBankCollection"],
  ["yieldBankNftAbi", "YieldBankNFT"],
  ["yieldBankMintStagePolicyAbi", "YieldBankMintStagePolicy"],
  ["yieldBankProceedsVaultAbi", "YieldBankProceedsVault"],
  ["yieldBankDistributorAbi", "YieldBankDistributor"],
  ["collectionPortfolioAllocatorAbi", "CollectionPortfolioAllocator"],
];

const declarations = [];
for (const [exportName, contractName] of contracts) {
  const artifactPath = resolve(contractsRoot, "out", `${contractName}.sol`, `${contractName}.json`);
  const artifact = JSON.parse(await readFile(artifactPath, "utf8"));
  if (!Array.isArray(artifact.abi)) throw new Error(`Missing ABI in ${artifactPath}`);
  declarations.push(`export const ${exportName} = ${JSON.stringify(artifact.abi, null, 2)} as const;`);
}

const output = [
  "// Generated by sdk/scripts/generate-abis.mjs. Do not edit manually.",
  "",
  ...declarations,
  "",
].join("\n");

await writeFile(resolve(sdkRoot, "src", "abis.generated.ts"), output);
